{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"imdb_movies\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.132.1053.0 (24.08)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "imdb_movie": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "imdb movie": {
                      "State": "Generated"
                    }
                  },
                  {
                    "imdb_movies": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "imdb show": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "imdb flick": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "imdb picture": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  },
                  {
                    "imdb film": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.485
                    }
                  }
                ]
              },
              "imdb_movie.ano": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Ano"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ano": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.ator_principal": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Ator_principal"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "ator principal": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Ator_principal": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  },
                  {
                    "ator leader": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "ator doyenne": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "ator doyen": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.475
                    }
                  },
                  {
                    "ator chief": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "ator head": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.461
                    }
                  },
                  {
                    "ator headmaster": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  },
                  {
                    "ator headmistress": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  },
                  {
                    "ator dean": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  },
                  {
                    "ator provost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.451
                    }
                  }
                ]
              },
              "imdb_movie.avaliação_imdb": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Avaliação_imdb"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "avaliação imdb": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Avaliação_imdb": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "imdb_movie.classificacao_idade": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Classificacao_Idade"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "classificacao idade": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Classificacao_Idade": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "imdb_movie.diretor": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Diretor"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "diretor": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.duracao_em_minutos_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "duracao em minutos (total)"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "duracao em minutos (total)": {
                      "State": "Generated"
                    }
                  },
                  {
                    "duracao em minuto (total)": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.78
                    }
                  },
                  {
                    "duracao em minutos": {
                      "State": "Generated",
                      "Weight": 0.75
                    }
                  }
                ]
              },
              "imdb_movie.genero": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Genero"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "genero": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.id": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "id"
                  }
                },
                "NameType": "Identifier",
                "State": "Generated",
                "Terms": [
                  {
                    "id": {
                      "State": "Generated"
                    }
                  },
                  {
                    "identification": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "identity": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.736
                    }
                  },
                  {
                    "credential": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.714
                    }
                  }
                ]
              },
              "imdb_movie.idioma": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Idioma"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "idioma": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.indicacoe": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Indicacoes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "indicacoe": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.local_filmagem": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Local_filmagem"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "local filmagem": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Local_filmagem": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "imdb_movie.orçamento": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Orçamento"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "orçamento": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.oscar": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Oscar"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "oscar": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.pais_origem": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Pais_origem"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "pais origem": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Pais_origem": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "imdb_movie.produtora": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Produtora"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "produtora": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.receita_bruta_mundial": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Receita_bruta_mundial"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "receita bruta mundial": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Receita_bruta_mundial": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "imdb_movie.receita_eua_canada": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Receita_eua_canada"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "receita eua canada": {
                      "State": "Generated"
                    }
                  },
                  {
                    "Receita_eua_canada": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "imdb_movie.roteirista": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Roteirista"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "roteirista": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.status_de_crítica": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "Status de Crítica"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "status de crítica": {
                      "State": "Generated"
                    }
                  },
                  {
                    "category de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "importance de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "prestige de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "prominence de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.609
                    }
                  },
                  {
                    "condition de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "class de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "grade de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "level de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "position de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  },
                  {
                    "rank de crítica": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.591
                    }
                  }
                ]
              },
              "imdb_movie.título": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "título"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "título": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "imdb_movie.voto": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "imdb_movies",
                    "ConceptualProperty": "voto"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "voto": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medida": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.contagem_de_filme": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "contagem de filme"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "contagem de filme": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.filmes_pos_2000": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Filmes Pos 2000"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "filmes pos 2000": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.lucro_ou_prejuizo": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Lucro ou Prejuizo"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "lucro ou prejuizo": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.lucro_total": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "lucro total"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "lucro total": {
                      "State": "Generated"
                    }
                  },
                  {
                    "lucro aggregate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  },
                  {
                    "lucro overall": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.727
                    }
                  }
                ]
              },
              "medida.margem": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "margem"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "margem": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.medias_notas_2000": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "medias_notas_2000"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "medias notas 2000": {
                      "State": "Generated"
                    }
                  },
                  {
                    "medias_notas_2000": {
                      "State": "Generated",
                      "Type": "Noun",
                      "Weight": 0.99
                    }
                  }
                ]
              },
              "medida.qtd__filmes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Qtd. Filmes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "qtd. filmes": {
                      "State": "Generated"
                    }
                  }
                ]
              },
              "medida.total_arrecadado": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Total Arrecadado"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total arrecadado": {
                      "State": "Generated"
                    }
                  },
                  {
                    "aggregate arrecadado": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall arrecadado": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "Arrecadado": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "medida.total_filmes": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Total Filmes"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total filmes": {
                      "State": "Generated"
                    }
                  },
                  {
                    "aggregate filme": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall filme": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "medida.total_oscars": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Total Oscars"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "total oscars": {
                      "State": "Generated"
                    }
                  },
                  {
                    "oscars": {
                      "State": "Generated",
                      "Weight": 0.97
                    }
                  },
                  {
                    "aggregate oscar": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  },
                  {
                    "overall oscar": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.582
                    }
                  }
                ]
              },
              "medida.value": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "Medidas",
                    "ConceptualProperty": "Value"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "value": {
                      "State": "Generated"
                    }
                  },
                  {
                    "assessment": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.491
                    }
                  },
                  {
                    "worth": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "price": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "cost": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "charge": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "rate": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.476
                    }
                  },
                  {
                    "importance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "significance": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "usefulness": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  },
                  {
                    "consequence": {
                      "Source": {
                        "Agent": "Thesaurus"
                      },
                      "State": "Suggested",
                      "Type": "Noun",
                      "Weight": 0.466
                    }
                  }
                ],
                "Visibility": {
                  "Value": "Hidden"
                }
              }
            },
            "Language": "en-US",
            "Relationships": {
              "imdb_movie_has_ano": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.ano"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_anos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.ano": {
                    "Target": {
                      "Entity": "imdb_movie.ano"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_ator_principal": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.ator_principal"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_ator_principals",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.ator_principal": {
                    "Target": {
                      "Entity": "imdb_movie.ator_principal"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_avaliação_imdb": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.avaliação_imdb"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_avaliação_imdbs",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.avaliação_imdb": {
                    "Target": {
                      "Entity": "imdb_movie.avaliação_imdb"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_classificacao_idade": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.classificacao_idade"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_classificacao_idades",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.classificacao_idade": {
                    "Target": {
                      "Entity": "imdb_movie.classificacao_idade"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_diretor": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.diretor"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_diretors",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.diretor": {
                    "Target": {
                      "Entity": "imdb_movie.diretor"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_duracao_em_minutos_total": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.duracao_em_minutos_total"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_duracao_em_minutos_total",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.duracao_em_minutos_total": {
                    "Target": {
                      "Entity": "imdb_movie.duracao_em_minutos_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_genero": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.genero"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_generos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.genero": {
                    "Target": {
                      "Entity": "imdb_movie.genero"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_id": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.id"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_ids",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "ID": "ids_are_names_IDs_of_imdb_movies",
                    "Name": {
                      "Name": {
                        "Role": "imdb_movie.id"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.id": {
                    "Target": {
                      "Entity": "imdb_movie.id"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_idioma": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.idioma"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_idiomas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.idioma": {
                    "Target": {
                      "Entity": "imdb_movie.idioma"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_indicacoe": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.indicacoe"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_indicacoes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.indicacoe": {
                    "Target": {
                      "Entity": "imdb_movie.indicacoe"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_local_filmagem": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.local_filmagem"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_local_filmagems",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.local_filmagem": {
                    "Target": {
                      "Entity": "imdb_movie.local_filmagem"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_contagem_de_filme": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.contagem_de_filme"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_contagem_de_filme",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.contagem_de_filme": {
                    "Target": {
                      "Entity": "medida.contagem_de_filme"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_filmes_pos_2000": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.filmes_pos_2000"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_filmes_pos_2000",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.filmes_pos_2000": {
                    "Target": {
                      "Entity": "medida.filmes_pos_2000"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_lucro_ou_prejuizo": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.lucro_ou_prejuizo"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_lucro_ou_prejuizo",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.lucro_ou_prejuizo": {
                    "Target": {
                      "Entity": "medida.lucro_ou_prejuizo"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_lucro_total": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.lucro_total"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_lucro_total",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.lucro_total": {
                    "Target": {
                      "Entity": "medida.lucro_total"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_margem": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.margem"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_margem",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.margem": {
                    "Target": {
                      "Entity": "medida.margem"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_medias_notas_2000": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.medias_notas_2000"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_medias_notas_2000",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.medias_notas_2000": {
                    "Target": {
                      "Entity": "medida.medias_notas_2000"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_qtd__filmes": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.qtd__filmes"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_qtd__filmes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.qtd__filmes": {
                    "Target": {
                      "Entity": "medida.qtd__filmes"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_total_arrecadado": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.total_arrecadado"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_total_arrecadado",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.total_arrecadado": {
                    "Target": {
                      "Entity": "medida.total_arrecadado"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_total_filmes": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.total_filmes"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_total_filmes",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.total_filmes": {
                    "Target": {
                      "Entity": "medida.total_filmes"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_medida_total_oscars": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "medida.total_oscars"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_total_oscars",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "medida.total_oscars": {
                    "Target": {
                      "Entity": "medida.total_oscars"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_orçamento": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.orçamento"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_orçamentos",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "imdb_movie.orçamento"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "orçamento_indicates_how_expensive_imdb_movies_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.orçamento": {
                    "Target": {
                      "Entity": "imdb_movie.orçamento"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_oscar": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.oscar"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_oscars",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.oscar": {
                    "Target": {
                      "Entity": "imdb_movie.oscar"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_pais_origem": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.pais_origem"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_pais_origems",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.pais_origem": {
                    "Target": {
                      "Entity": "imdb_movie.pais_origem"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_produtora": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.produtora"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_produtoras",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.produtora": {
                    "Target": {
                      "Entity": "imdb_movie.produtora"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_receita_bruta_mundial": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.receita_bruta_mundial"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_receita_bruta_mundial",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "imdb_movie.receita_bruta_mundial"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "receita_bruta_mundial_indicates_how_expensive_imdb_movies_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.receita_bruta_mundial": {
                    "Target": {
                      "Entity": "imdb_movie.receita_bruta_mundial"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_receita_eua_canada": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.receita_eua_canada"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_receita_eua_canada",
                    "State": "Generated",
                    "Weight": 0.99
                  },
                  {
                    "Adjective": {
                      "Adjectives": [
                        {
                          "expensive": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Antonyms": [
                        {
                          "cheap": {
                            "State": "Generated"
                          }
                        }
                      ],
                      "Measurement": {
                        "Role": "imdb_movie.receita_eua_canada"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "receita_eua_canada_indicates_how_expensive_imdb_movies_are",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.receita_eua_canada": {
                    "Target": {
                      "Entity": "imdb_movie.receita_eua_canada"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_roteirista": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.roteirista"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_roteiristas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.roteirista": {
                    "Target": {
                      "Entity": "imdb_movie.roteirista"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_status_de_crítica": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.status_de_crítica"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_status_de_críticas",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.status_de_crítica": {
                    "Target": {
                      "Entity": "imdb_movie.status_de_crítica"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_título": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.título"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_títulos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.título": {
                    "Target": {
                      "Entity": "imdb_movie.título"
                    }
                  }
                },
                "State": "Generated"
              },
              "imdb_movie_has_voto": {
                "Binding": {
                  "ConceptualEntity": "imdb_movies"
                },
                "Phrasings": [
                  {
                    "Attribute": {
                      "Object": {
                        "Role": "imdb_movie.voto"
                      },
                      "Subject": {
                        "Role": "imdb_movie"
                      }
                    },
                    "ID": "imdb_movies_have_votos",
                    "State": "Generated",
                    "Weight": 0.99
                  }
                ],
                "Roles": {
                  "imdb_movie": {
                    "Target": {
                      "Entity": "imdb_movie"
                    }
                  },
                  "imdb_movie.voto": {
                    "Target": {
                      "Entity": "imdb_movie.voto"
                    }
                  }
                },
                "State": "Generated"
              }
            },
            "Version": "3.5.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "imdb_movies",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "título",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2141ce99-f80d-4296-b223-79ab681790ac",
            "sourceColumn": "título",
            "summarizeBy": "none"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c79c76ae-26f8-41e3-a64f-b059098e5f68",
            "sourceColumn": "Ano",
            "summarizeBy": "sum"
          },
          {
            "name": "Classificacao_Idade",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0ac177de-4b38-47f2-a63f-bb157961bff6",
            "sourceColumn": "Classificacao_Idade",
            "summarizeBy": "none"
          },
          {
            "name": "Avaliação_imdb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "2face021-b5a7-41a0-bc03-9b2f4ab82a8f",
            "sourceColumn": "Avaliação_imdb",
            "summarizeBy": "sum"
          },
          {
            "name": "voto",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "17e94265-4d95-4a6a-a928-c1267d4f500e",
            "sourceColumn": "voto",
            "summarizeBy": "sum"
          },
          {
            "name": "Orçamento",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "1f99a57a-a0ee-4c15-84b3-9a488c7d7ddc",
            "sourceColumn": "Orçamento",
            "summarizeBy": "sum"
          },
          {
            "name": "Receita_bruta_mundial",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "cfe54afc-3b20-487f-9435-63c5bd618976",
            "sourceColumn": "Receita_bruta_mundial",
            "summarizeBy": "sum"
          },
          {
            "name": "Receita_eua_canada",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "1e6634f5-c998-469a-a0f8-27e09351f3bd",
            "sourceColumn": "Receita_eua_canada",
            "summarizeBy": "sum"
          },
          {
            "name": "Diretor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18cd7866-b0c1-44b2-99a0-d6e10e6ff97d",
            "sourceColumn": "Diretor",
            "summarizeBy": "none"
          },
          {
            "name": "Roteirista",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61ed2be7-7f4e-4e14-a05f-e5b307896e6a",
            "sourceColumn": "Roteirista",
            "summarizeBy": "none"
          },
          {
            "name": "Ator_principal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9a3a4c47-8479-47aa-a07d-20bda625341c",
            "sourceColumn": "Ator_principal",
            "summarizeBy": "none"
          },
          {
            "name": "Genero",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "85b1169f-83af-4afb-9c23-3d9b5d6c32c0",
            "sourceColumn": "Genero",
            "summarizeBy": "none"
          },
          {
            "name": "duracao em minutos (total)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "24d99850-c6e4-4c1c-a8d9-a544cf3dee07",
            "sourceColumn": "duracao em minutos (total)",
            "summarizeBy": "none"
          },
          {
            "name": "Pais_origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bc678a9e-409a-4456-8ae1-5ce68d15c720",
            "sourceColumn": "Pais_origem",
            "summarizeBy": "none"
          },
          {
            "name": "Local_filmagem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b94177b7-6158-4767-be1a-48edca152f05",
            "sourceColumn": "Local_filmagem",
            "summarizeBy": "none"
          },
          {
            "name": "Produtora",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1bb8070e-b08a-4e48-b513-f84fb44ffbd2",
            "sourceColumn": "Produtora",
            "summarizeBy": "none"
          },
          {
            "name": "Idioma",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "75da1df2-820e-47cd-ad31-952e3aad55e3",
            "sourceColumn": "Idioma",
            "summarizeBy": "none"
          },
          {
            "name": "Indicacoes",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b64fc4bc-71a0-449c-ab3f-07f79ec53ad8",
            "sourceColumn": "Indicacoes",
            "summarizeBy": "sum"
          },
          {
            "name": "Oscar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "78ab88af-8a72-4279-991f-008ff85771a6",
            "sourceColumn": "Oscar",
            "summarizeBy": "sum"
          },
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "acb411d6-78ca-4470-b1f3-345c6ef5e308",
            "sourceColumn": "id",
            "summarizeBy": "none"
          },
          {
            "name": "Status de Crítica",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": [
              "",
              "IF(",
              "    imdb_movies[Avaliação_imdb] >= 80,",
              "    \"Excelente\",",
              "    \"Comum\"",
              ")"
            ],
            "isDataTypeInferred": true,
            "lineageTag": "12618229-dba4-4b42-99d1-c2927f543dae",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "f3513022-d5ae-4e28-803a-066d5bd0eadc",
        "partitions": [
          {
            "name": "imdb_movies",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Csv.Document(File.Contents(\"C:\\Users\\sophia.silva\\Desktop\\projeto_imdb\\filmes_nova - world_imdb_movies_top_movies_per_year.csv\"),[Delimiter=\",\", Columns=24, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(Fonte,{{\"Column1\", type text}, {\"Column2\", type text}, {\"Column3\", type text}, {\"Column4\", type text}, {\"Column5\", type text}, {\"Column6\", type text}, {\"Column7\", type text}, {\"Column8\", type text}, {\"Column9\", type text}, {\"Column10\", type text}, {\"Column11\", type text}, {\"Column12\", type text}, {\"Column13\", type text}, {\"Column14\", type text}, {\"Column15\", type text}, {\"Column16\", type text}, {\"Column17\", type text}, {\"Column18\", type text}, {\"Column19\", type text}, {\"Column20\", type text}, {\"Column21\", type text}, {\"Column22\", type text}, {\"Column23\", type text}, {\"Column24\", type text}}),",
                "    #\"Linhas Superiores Removidas\" = Table.Skip(#\"Tipo Alterado\",2),",
                "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(#\"Linhas Superiores Removidas\", [PromoteAllScalars=true]),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Cabeçalhos Promovidos\",{{\"id\", type text}, {\"title\", type text}, {\"link\", type text}, {\"year\", Int64.Type}, {\"duration\", type text}, {\"rating_mpa\", type text}, {\"rating_imdb\", Int64.Type}, {\"vote\", Int64.Type}, {\"budget\", Int64.Type}, {\"gross_world_wide\", Int64.Type}, {\"gross_us_canada\", Currency.Type}, {\"gross_opening_weekend\", Int64.Type}, {\"director\", type text}, {\"writer\", type text}, {\"star\", type text}, {\"genre\", type text}, {\"country_origin\", type text}, {\"filming_location\", type text}, {\"production_company\", type text}, {\"language\", type text}, {\"captions\", type text}, {\"win\", Int64.Type}, {\"nomination\", Int64.Type}, {\"oscar\", Int64.Type}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Tipo Alterado1\",{\"link\", \"captions\", \"gross_opening_weekend\"}),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(#\"Colunas Removidas\", each true),",
                "    #\"Colunas Removidas1\" = Table.RemoveColumns(#\"Linhas Filtradas\",{\"win\"}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Colunas Removidas1\", {\"id\"}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Duplicatas Removidas\",{{\"title\", \"título\"}, {\"year\", \"ano\"}, {\"duration\", \"duração\"}, {\"rating_imdb\", \"avaliação_imdb\"}, {\"vote\", \"voto\"}, {\"budget\", \"orçamento\"}, {\"gross_world_wide\", \"receita_bruta_mundial\"}, {\"gross_us_canada\", \"receita_eua_canada\"}, {\"director\", \"diretor\"}, {\"writer\", \"roteirista\"}, {\"star\", \"ator_principal\"}, {\"genre\", \"genero\"}, {\"country_origin\", \"pais_origem\"}, {\"filming_location\", \"local_filmagem\"}, {\"production_company\", \"produtora\"}, {\"language\", \"idioma\"}, {\"nomination\", \"indicacoes\"}, {\"rating_mpa\", \"classificacao_idade\"}}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Colunas Renomeadas\",{{\"ano\", Int64.Type}, {\"orçamento\", Currency.Type}, {\"receita_bruta_mundial\", Currency.Type}, {\"receita_eua_canada\", Currency.Type}}),",
                "    #\"Texto em Maiúscula\" = Table.TransformColumns(#\"Tipo Alterado2\",{{\"título\", Text.Upper, type text}}),",
                "    #\"Colocar Cada Palavra Em Maiúscula\" = Table.TransformColumns(#\"Texto em Maiúscula\",{{\"título\", Text.Proper, type text}}),",
                "    #\"Texto em Maiúscula1\" = Table.TransformColumns(#\"Colocar Cada Palavra Em Maiúscula\",{{\"título\", Text.Upper, type text}}),",
                "    #\"Texto Extraído Antes do Delimitador\" = Table.TransformColumns(#\"Texto em Maiúscula1\", {{\"genero\", each Text.BeforeDelimiter(_, \",\"), type text}}),",
                "    #\"Linhas em Branco Removidas\" = Table.SelectRows(#\"Texto Extraído Antes do Delimitador\", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {\"\", null}))),",
                "    #\"Erros Removidos\" = Table.RemoveRowsWithErrors(#\"Linhas em Branco Removidas\", {\"avaliação_imdb\"}),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Erros Removidos\",{{\"ano\", \"Ano\"}, {\"duração\", \"Duração\"}, {\"classificacao_idade\", \"Classificacao_Idade\"}, {\"avaliação_imdb\", \"Avaliação_imdb\"}, {\"orçamento\", \"Orçamento\"}, {\"receita_bruta_mundial\", \"Receita_bruta_mundial\"}, {\"receita_eua_canada\", \"Receita_eua_canada\"}, {\"diretor\", \"Diretor\"}, {\"roteirista\", \"Roteirista\"}, {\"ator_principal\", \"Ator_principal\"}, {\"genero\", \"Genero\"}, {\"pais_origem\", \"Pais_origem\"}, {\"local_filmagem\", \"Local_filmagem\"}, {\"produtora\", \"Produtora\"}, {\"idioma\", \"Idioma\"}, {\"indicacoes\", \"Indicacoes\"}, {\"oscar\", \"Oscar\"}}),",
                "    #\"Texto Inserido Antes do Delimitador\" = Table.AddColumn(#\"Colunas Renomeadas1\", \"Texto Antes do Delimitador\", each Text.BeforeDelimiter([Duração], \"h\"), type text),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Texto Inserido Antes do Delimitador\",{{\"Texto Antes do Delimitador\", \"Horas\"}}),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Colunas Renomeadas2\",{{\"Horas\", Int64.Type}}),",
                "    #\"Erros Removidos1\" = Table.RemoveRowsWithErrors(#\"Tipo Alterado3\", {\"Horas\"}),",
                "    #\"Texto Inserido Entre os Delimitadores\" = Table.AddColumn(#\"Erros Removidos1\", \"Texto Entre os Delimitadores\", each Text.BetweenDelimiters([Duração], \" \", \"m\"), type text),",
                "    #\"Colunas Renomeadas3\" = Table.RenameColumns(#\"Texto Inserido Entre os Delimitadores\",{{\"Texto Entre os Delimitadores\", \"Minutos\"}}),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Colunas Renomeadas3\",{{\"Minutos\", Int64.Type}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado4\", \"Personalizar\", each ([Horas]*60)+[Minutos]),",
                "    #\"Colunas Renomeadas4\" = Table.RenameColumns(#\"Personalização Adicionada\",{{\"Personalizar\", \"duracao em minutos (total)\"}}),",
                "    #\"Colunas Removidas2\" = Table.RemoveColumns(#\"Colunas Renomeadas4\",{\"Minutos\", \"Horas\", \"Duração\"}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Removidas2\",{\"id\", \"título\", \"Ano\", \"Classificacao_Idade\", \"Avaliação_imdb\", \"voto\", \"Orçamento\", \"Receita_bruta_mundial\", \"Receita_eua_canada\", \"Diretor\", \"Roteirista\", \"Ator_principal\", \"Genero\", \"duracao em minutos (total)\", \"Pais_origem\", \"Local_filmagem\", \"Produtora\", \"Idioma\", \"Indicacoes\", \"Oscar\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Colunas Reordenadas\",\"\",\"Desconhecido\",Replacer.ReplaceValue,{\"Local_filmagem\"})",
                "in",
                "    #\"Valor Substituído\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_200e31f0-ee15-42ae-a4f0-048366412320",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "867e3f07-0e87-4faa-b844-12c993f071f9",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "a30cd0b9-7105-40a9-a4bd-44dd4ba33fb3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "37c84497-a1af-417e-a44b-5f9f02db590e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c30b79a8-ec9b-4a7d-9c2b-4efdb7a80350",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "77d82762-668e-4c1d-98f3-af6252cc1fa3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6d756b5a-4e02-4af6-8cd8-3cbf2b8764ab",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "0dad6df1-b779-44e9-a66d-b51e74ba16a6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "d49d2332-855a-4d93-ab52-e5edca492197",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "ab569505-7d37-4f81-bc47-33e248a296bf",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "d79eecd1-10f2-446c-8a4b-6293da227a7a",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "1dbd35bb-f965-4497-b56a-6260f85a6939",
                "ordinal": 3
              }
            ],
            "lineageTag": "7d1facf4-7ebf-4b29-aa9f-125c8fa0145d"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "93320757-2663-4763-9964-9136297f01fa",
        "partitions": [
          {
            "name": "DateTableTemplate_200e31f0-ee15-42ae-a4f0-048366412320",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Medidas",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "c3999c88a6ea4e5eb00930a8bbfa1936"
          }
        ],
        "columns": [
          {
            "name": "Value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ea307583-d3b5-4a1d-b691-350e2fd9cb1e",
            "sourceColumn": "[Value]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "ee95a541-291d-4565-96b8-c79077f7210b",
        "measures": [
          {
            "name": "Qtd. Filmes",
            "expression": "COUNT(imdb_movies[id])",
            "formatString": "0",
            "lineageTag": "709adc16-3e64-4357-837a-2f2cc7b35df3"
          },
          {
            "name": "contagem de filme",
            "expression": "DISTINCTCOUNT(imdb_movies[id])",
            "formatString": "0",
            "lineageTag": "df262b79-b297-42fc-9608-abf4b609d0c3"
          },
          {
            "name": "lucro total",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUMX(imdb_movies, imdb_movies[Receita_bruta_mundial] - imdb_movies[Orçamento])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "e371a89f-515d-4b91-ad30-198cc9e426ee"
          },
          {
            "name": "medias_notas_2000",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": "CALCULATE(AVERAGE('imdb_movies'[Avaliação_imdb]), 'imdb_movies'[Ano] >= 2000)",
            "lineageTag": "de002396-5a6c-4673-84c9-3360deb99549"
          },
          {
            "name": "margem",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(imdb_movies[Receita_bruta_mundial])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "1c43b7de-c660-43a5-b908-5deddb1f263e"
          },
          {
            "name": "Lucro ou Prejuizo",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUMX(imdb_movies, imdb_movies[Receita_bruta_mundial] - imdb_movies[Orçamento])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "75213887-2bf4-40f4-9bd8-c2e04641a56b"
          },
          {
            "name": "Total Arrecadado",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "SUM(imdb_movies[Receita_bruta_mundial])",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "e6a9b92b-1278-475f-94cd-1aee291ec79b"
          },
          {
            "name": "Filmes Pos 2000",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNT(imdb_movies[id]),",
              "    imdb_movies[Ano] >= 2000",
              ")"
            ],
            "formatString": "0",
            "lineageTag": "7996847e-ddd4-424d-a680-b3436b76bad4"
          },
          {
            "name": "Total Filmes",
            "expression": "COUNT(imdb_movies[id])",
            "formatString": "0",
            "lineageTag": "cb93c397-b7b0-44ee-bae2-6f4afe5b2612"
          },
          {
            "name": "Total Oscars",
            "expression": "SUM(imdb_movies[Oscar])",
            "formatString": "0",
            "lineageTag": "9327aa4a-5549-4d8b-8e37-9cb91149f496"
          }
        ],
        "partitions": [
          {
            "name": "Medidas",
            "mode": "import",
            "source": {
              "expression": "{BLANK()}",
              "type": "calculated"
            }
          }
        ]
      }
    ]
  }
}